name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.0', '8.2', '8.4', '8.6', '8.8', '8.10', '9.0']
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Build
      run: cabal build
    - name: Haddock
      run: cabal haddock

  build-freebsd:
    # This job intentionally is using macOS because at the time of the writing
    # Linux and Windows environments don't have the necessary virtualization features.
    # See https://github.com/vmactions/freebsd-vm#under-the-hood.
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      id: build-freebsd
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        mem: 4096
        prepare: pkg install -y ghc hs-cabal-install git
        # Virtual machine does not allow to leverage cache
        # and is quite slow, so only tests are run.
        run: |
          cabal update
          cabal build
